//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Localization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice.
        /// </summary>
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create job.
        /// </summary>
        internal static string menu_create {
            get {
                return ResourceManager.GetString("menu_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job.
        /// </summary>
        internal static string menu_delete {
            get {
                return ResourceManager.GetString("menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit job.
        /// </summary>
        internal static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List jobs.
        /// </summary>
        internal static string menu_list {
            get {
                return ResourceManager.GetString("menu_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string menu_quit {
            get {
                return ResourceManager.GetString("menu_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run job.
        /// </summary>
        internal static string menu_run {
            get {
                return ResourceManager.GetString("menu_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run all jobs.
        /// </summary>
        internal static string menu_run_all {
            get {
                return ResourceManager.GetString("menu_run_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave.
        /// </summary>
        internal static string menu_title {
            get {
                return ResourceManager.GetString("menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name:.
        /// </summary>
        internal static string prompt_name {
            get {
                return ResourceManager.GetString("prompt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select job:.
        /// </summary>
        internal static string prompt_select {
            get {
                return ResourceManager.GetString("prompt_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source:.
        /// </summary>
        internal static string prompt_source {
            get {
                return ResourceManager.GetString("prompt_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target:.
        /// </summary>
        internal static string prompt_target {
            get {
                return ResourceManager.GetString("prompt_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type (1=Full, 2=Diff):.
        /// </summary>
        internal static string prompt_type {
            get {
                return ResourceManager.GetString("prompt_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current log format.
        /// </summary>
        internal static string settings_current_format {
            get {
                return ResourceManager.GetString("settings_current_format", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose format (1=JSON, 2=XML):.
        /// </summary>
        internal static string settings_choose_format {
            get {
                return ResourceManager.GetString("settings_choose_format", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log format updated. Restart to apply.
        /// </summary>
        internal static string settings_format_saved {
            get {
                return ResourceManager.GetString("settings_format_saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice.
        /// </summary>
        internal static string settings_invalid {
            get {
                return ResourceManager.GetString("settings_invalid", resourceCulture);
            }
        }
    }
}
